### PR TITLE
Building Logic to play the game "Tic Tac Toe"

### PR DESCRIPTION
**Pull request by deepak-prajapatii**
#### Domain:

- Android App
-  Building Logics

#### What learners actually learn

- How to Build Logic for any app
-  Android Development

#### Activities for learners

- Improve the layout and fix issues like Ids, string values, etc.
-  Fix Java Code in MainActivity.java
-  There is already some code written for learner convenience, you need to fix the issues and  add some logic.

### CODE REVIEW

**Comment by Kevinpaulose05** [comment]
There is no need to open/close a PR multiple times. Just keep pushing ur code and the PR will get updated. It is better for u to keep track of changes and also to have efficient workflow

**Comment by YourAKShaw** [comment]
@deepak-prajapatii Kindly follow the CONTRIBUTING.md properly. Check the updated one in the upstream/main branch. We've added templates for issues and PRs. 

Kindly follow the references below for details regarding the format for description.
This is how an issue should look like: https://github.com/Crio-Bytes/Miscellaneous/issues/3

**Comment by deepak-prajapatii** [comment]
@Ak-Shaw Can you again check my PR.

**Review by Kevinpaulose05 — COMMENTED** [review]
Hey @deepak-prajapatii . Nice work. But we can't accept this PR as it is now. Kindly give more documentation in both activities. Try and give as many resource links as you can with proper indication and structure. As of now only an android developer can figure out your PR. There is not much to do. Just increase the documentation so that a new person can follow your microbyte and still be able to do it on his/her own comfortably. **Caution:** Don't make it like a tutorial, give resource links which learners have to follow and work to understand ur project. Through each steps u can add code snippets(hide some code so that contributors can complete it in the form of an issue) that will give ppl an better experience.
Cheers

**Comment by deepak-prajapatii** [comment]
> Hey @deepak-prajapatii . Nice work. But we can't accept this PR as it is now. Kindly give more documentation in both activities. Try and give as many resource links as you can with proper indication and structure. As of now only an android developer can figure out your PR. There is not much to do. Just increase the documentation so that a new person can follow your microbyte and still be able to do it on his/her own comfortably. **Caution:** Don't make it like a tutorial, give resource links which learners have to follow and work to understand ur project. Through each steps u can add code snippets(hide some code so that contributors can complete it in the form of an issue) that will give ppl an better experience.
> Cheers

Thanks for guiding me. I'll try my best.

**Comment by deepak-prajapatii** [comment]
> Hey @deepak-prajapatii . Nice work. But we can't accept this PR as it is now. Kindly give more documentation in both activities. Try and give as many resource links as you can with proper indication and structure. As of now only an android developer can figure out your PR. There is not much to do. Just increase the documentation so that a new person can follow your microbyte and still be able to do it on his/her own comfortably. **Caution:** Don't make it like a tutorial, give resource links which learners have to follow and work to understand ur project. Through each steps u can add code snippets(hide some code so that contributors can complete it in the form of an issue) that will give ppl an better experience.
> Cheers

Can you litle bit explain me how can I add documentation. Please give me some hints.

**Comment by Kevinpaulose05** [comment]
> > Hey @deepak-prajapatii . Nice work. But we can't accept this PR as it is now. Kindly give more documentation in both activities. Try and give as many resource links as you can with proper indication and structure. As of now only an android developer can figure out your PR. There is not much to do. Just increase the documentation so that a new person can follow your microbyte and still be able to do it on his/her own comfortably. **Caution:** Don't make it like a tutorial, give resource links which learners have to follow and work to understand ur project. Through each steps u can add code snippets(hide some code so that contributors can complete it in the form of an issue) that will give ppl an better experience.
> > Cheers
> 
> Can you litle bit explain me how can I add documentation. Please give me some hints.

Suppose u r a newbie to the microbyte. As you go through the microbyte you will have certain terms,functions,syntax,etc. doubts/thoughts right? Google about it. Public forums like Stackoverflow, github itself,geeksforgeeks,w3schools, even youtube will do. All softwares and tools' official website have documentation, like [this](https://developer.android.com/studio/intro) or [this](https://docs.oracle.com/en/java/index.html). Keep searching for references that will make enables all noob to pro to interact and learn from ur microbyte

**Comment by deepak-prajapatii** [comment]
> > > Hey @deepak-prajapatii . Nice work. But we can't accept this PR as it is now. Kindly give more documentation in both activities. Try and give as many resource links as you can with proper indication and structure. As of now only an android developer can figure out your PR. There is not much to do. Just increase the documentation so that a new person can follow your microbyte and still be able to do it on his/her own comfortably. **Caution:** Don't make it like a tutorial, give resource links which learners have to follow and work to understand ur project. Through each steps u can add code snippets(hide some code so that contributors can complete it in the form of an issue) that will give ppl an better experience.
> > > Cheers
> > 
> > 
> > Can you litle bit explain me how can I add documentation. Please give me some hints.
> 
> Suppose u r a newbie to the microbyte. As you go through the microbyte you will have certain terms,functions,syntax,etc. doubts/thoughts right? Google about it. Public forums like Stackoverflow, github itself,geeksforgeeks,w3sv=chools, even youtube will do. All softwares and tools' official website have documentation, like [this](https://developer.android.com/studio/intro) or [this](https://docs.oracle.com/en/java/index.html). Keep searching for references that will make enables all noob to pro to interact and learn from ur microbyte

Okay I'll try

**Comment by YourAKShaw** [comment]
Umm.. @deepak-prajapatii , by mistake you've jumbled up between issue and PR. [This](https://github.com/Crio-Bytes/Miscellaneous/issues/3) should be what an issue should look like and [this](https://github.com/Crio-Bytes/Miscellaneous/pull/1) should be what a PR should look like. Just copy paste what you currently have here in the description as a new issue and make room for our PR template.

If you still have queries, feel free to reach out to the maintainers and we'll sort it out for you.

**Pull request closed without merging**
