### PR TITLE
activity-5 solved

### LINKED ISSUE #63: [Learners/Creators] Solve the DIY Challenge
**MicroByte Title:** COVID-19 Visualization using Pandas and Matplotlib

**Improvement Proposal:** 
- Solve the DIY challenge in your own way to get the output as mentioned in the bottom of the [README.md](https://github.com/Crio-Bytes/Miscellaneous/blob/main/COVID-19%20Visualization%20using%20Pandas%20and%20Matplotlib/README.md) file.

**Benefits of proposed improvements:** 
- Contributors will challenge their skills in Pandas and matplotlib libraries of python by solving this DIY challenge.
- A shoutout in slack from me.

All The Best!!

### PR DESCRIPTION
**Pull request by itsadityagupta**
# Closes #63 

### Checklist

- [x] Added/updated activities for learners
- [x] Solved Activity 5
- [x] Added Solution under the folder **Activity 5**
- [x] Followed a LearnByDoing approach
- [x] Clean and well-documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Review by amoghrajesh — APPROVED** [review]
Hey @Aditya-Gupta1!
Looks like you have solved it!
I have no complaints about the way you solved it. 
Good work, man 😄

**Comment by itsadityagupta** [comment]
Thanks @amoghrajesh !

**Review by Kevinpaulose05 — APPROVED** [review]
Nice work here. @Aditya-Gupta1 don't work on the issues now. U r a good creator. Try contributing more thru creating microbytes now, as we need them right now. U can work on the issues later. Because solving the issues will more or less put u under the learner category.

Anyways no worries. Kindly spend time on creating new microbytes from now. Hope u get my point. 

Happy Contributing!!

**Comment by itsadityagupta** [comment]
@Kevinpaulose05 I am working on a micro byte simultaneously.

**Comment by YourAKShaw** [comment]
@Aditya-Gupta1 That's awesome! :100: We're gladly waiting for it. Don't forget to follow the proper workflow of creating issues and PRs with proper descriptions.

**Pull request merged**
