### PR TITLE
Detailed Data Analysis

### LINKED ISSUE #39: [Creators] Add a detailed data analysis activity
**MicroByte Title:** Linear Regression with Regularization

**Improvement Proposal:** 

Make an activity preceding the first activity in the micro-byte, which does the following:
* Performs a detailed Data Analysis for the given dataset.
* Perform outlier detection and removal.
* Perform Feature Engineering.
* Perform Feature Selection.
* Save the preprocessed data frame along with the original dataset.

After you have the preprocessed form of the dataset, you can extend **Activity 1** by using a different linear regression model trained on new preprocessed data and show the reduction in error which a simple preprocessing can lead to.

**Benefits of proposed improvements:**

Users will get a practical intuition of the increase in the performance or reduction in the error, to which a carefully preprocessed dataset can lead to

### PR DESCRIPTION
**Pull request by rutujak24**
## Closes #39 

<Put a x between the square brackets. Make sure you get them all>

### Checklist: 

- [x] Added activities for learners
- [x] Didn't give the solutions to the added activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well-documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Comment by sudhanshutiwari264** [comment]
@rutujak24 your pr is under review!

**Review by amoghrajesh — CHANGES_REQUESTED** [review]
Hey @rutujak24 !
This is some great analysis that you have posted.
I like the way you have blurred out the code lines and shown the graph which will make the learners explore how you arrived at it.
However, I want to request a few small changes:

1.  The initial part where you explain what EDA is, you can make it a bit more concise.
2. You have blurred out the code and shown the graph, please make a mention of it at the top only so that learners don't think that the graph came magically. 
3. Also, make a mention of the fact that resources that a learner might use are available below :)

Apart from all this, great work!
Please make these changes at the earliest and notify us :)

**Comment by itsadityagupta** [comment]
Hey, @amoghrajesh I'm sorry but when I was reviewing @rutujak24 's code, I can't find any blurred code as you mentioned. What I can see is an empty cell and a graph in its output.
image

Correct me if I am wrong.
Thanks.

**Comment by amoghrajesh** [comment]
Hey @Aditya-Gupta1!
When I said blurred code, I meant "Empty cells" itself.
My intention was to say that output without input is provided which is great :)

**Comment by itsadityagupta** [comment]
> Hey @Aditya-Gupta1!
> When I said blurred code, I meant "Empty cells" itself.
> My intention was to say that output without input is provided which is great :)

Oh!

**Review by Kevinpaulose05 — APPROVED** [review]
As I mentioned before, you should leave some comments in the empty cells. Leaving it blank does not give it a good appeal. Slightly edit it when u get time. Don't keep this first priority for now. 

Awesome work is done. Keep up the work. Keep contributing!!

**Comment by Kevinpaulose05** [comment]
@rutujak24 Continue with the initial PR u make. Making new ones will confuse us and maintaining a single PR is essential for us to keep track of things. I hope u understand and pls keep this in mind in the future :)

**Review by amoghrajesh — APPROVED** [review]
Hey @rutujak24 !
Amazing work by making the changes. Now it will be very clear for learners as to what they are doing. 
Again, Great work!
Merging it 👍🏽

**Comment by rutujak24** [comment]
> Hey @rutujak24 !
> Amazing work by making the changes. Now it will be very clear for learners as to what they are doing.
> Again, Great work!
> Merging it 👍🏽

Thanks :)

**Comment by amoghrajesh** [comment]
@all-contributors kindly add @rutujak24  for:

- [x] code
- [x] content

**Pull request merged**
