### PR TITLE
Detailed Data Analysis

### LINKED ISSUE #39: [Creators] Add a detailed data analysis activity
**MicroByte Title:** Linear Regression with Regularization

**Improvement Proposal:** 

Make an activity preceding the first activity in the micro-byte, which does the following:
* Performs a detailed Data Analysis for the given dataset.
* Perform outlier detection and removal.
* Perform Feature Engineering.
* Perform Feature Selection.
* Save the preprocessed data frame along with the original dataset.

After you have the preprocessed form of the dataset, you can extend **Activity 1** by using a different linear regression model trained on new preprocessed data and show the reduction in error which a simple preprocessing can lead to.

**Benefits of proposed improvements:**

Users will get a practical intuition of the increase in the performance or reduction in the error, to which a carefully preprocessed dataset can lead to

### PR DESCRIPTION
**Pull request by rutujak24**
## Closes #39 

<Put a x between the square brackets. Make sure you get them all>

### Checklist: 

- [x] Added activities for learners
- [x] Didn't give the solutions to the added activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Comment by rutujak24** [comment]
@Aditya-Gupta1  Please review this

**Comment by YourAKShaw** [comment]
@rutujak24 You PR is under review. Till then, kindly edit your PR description and follow [this](https://github.com/Crio-Bytes/Miscellaneous/blob/main/.github/PULL_REQUEST_TEMPLATE/updating-microbyte.md) template for the same.

**Comment by rutujak24** [comment]
> @rutujak24 You PR is under review. Till then, kindly edit your PR description and follow [this](https://github.com/Crio-Bytes/Miscellaneous/blob/main/.github/PULL_REQUEST_TEMPLATE/updating-microbyte.md) template for the same.

All Done!

**Review by Kevinpaulose05 — CHANGES_REQUESTED** [review]
So, Firstly nice work. I see u have covered pretty much all checkpoints suggested by @Aditya-Gupta1 . Now there are a couple of things to be done.

1. Hide the main driving code. Codes like .head() and labelling can be kept. but codes that involve even a slight logic should be hid. Instead of the code mention a hint as a comment. But keep the output as it is. So what I suggest is after running the entire juyter notebook comment out the hints as mentioned.
I agree this is a bit painful to do bt now u have quality addition and ppl need to learn from ur code, not follow them step by step. Something like [this](https://github.com/Crio-Bytes/Miscellaneous/blob/main/COVID-19%20Visualization%20using%20Pandas%20and%20Matplotlib/src/Activity_3.ipynb). To save time don't document stuff but just comment the code as a hint.
2. Also when u download the .ipynb file kindly make sure u get rid of the errors first. The error are mainly type errors or some local package errors(right?). That may mislead or dimish the beauty of ur code.

All this should pretty much take half an hour or so. Try as much as time permits u to do. 
I have also requested @Aditya-Gupta1 for a review, to see if you have satisfied his ideation.

Don't worry, ur contribution is quality work. Just u have to restructure it according to our motto.

Reach out to us if u have any queries.

**Comment by Kevinpaulose05** [comment]
Also, I researched u a bit and I say can u work as a creator? U have quite a stellar profile and u can make some potential contributions to microbytes. Go through some of the repos in miscellaneous to get an idea of what is expected from a creator. Maybe convert some good project of yours into a microbyte. 

Cheers

**Comment by rutujak24** [comment]
> So, Firstly nice work. I see u have covered pretty much all checkpoints suggested by @Aditya-Gupta1 . Now there are a couple of things to be done.
> 
> 1. Hide the main driving code. Codes like .head() and labelling can be kept. but codes that involve even a slight logic should be hid. Instead of the code mention a hint as a comment. But keep the output as it is. So what I suggest is after running the entire juyter notebook comment out the hints as mentioned.
>    I agree this is a bit painful to do bt now u have quality addition and ppl need to learn from ur code, not follow them step by step. Something like [this](https://github.com/Crio-Bytes/Miscellaneous/blob/main/COVID-19%20Visualization%20using%20Pandas%20and%20Matplotlib/src/Activity_3.ipynb). To save time don't document stuff but just comment the code as a hint.
> 2. Also when u download the .ipynb file kindly make sure u get rid of the errors first. The error are mainly type errors or some local package errors(right?). That may mislead or dimish the beauty of ur code.
> 
> All this should pretty much take half an hour or so. Try as much as time permits u to do.
> I have also requested @Aditya-Gupta1 for a review, to see if you have satisfied his ideation.
> 
> Don't worry, ur contribution is quality work. Just u have to restructure it according to our motto.
> 
> Reach out to us if u have a

**Comment by rutujak24** [comment]
> So, Firstly nice work. I see u have covered pretty much all checkpoints suggested by @Aditya-Gupta1 . Now there are a couple of things to be done.
> 
> 1. Hide the main driving code. Codes like .head() and labelling can be kept. but codes that involve even a slight logic should be hid. Instead of the code mention a hint as a comment. But keep the output as it is. So what I suggest is after running the entire juyter notebook comment out the hints as mentioned.
>    I agree this is a bit painful to do bt now u have quality addition and ppl need to learn from ur code, not follow them step by step. Something like [this](https://github.com/Crio-Bytes/Miscellaneous/blob/main/COVID-19%20Visualization%20using%20Pandas%20and%20Matplotlib/src/Activity_3.ipynb). To save time don't document stuff but just comment the code as a hint.
> 2. Also when u download the .ipynb file kindly make sure u get rid of the errors first. The error are mainly type errors or some local package errors(right?). That may mislead or dimish the beauty of ur code.
> 
> All this should pretty much take half an hour or so. Try as much as time permits u to do.
> I have also requested @Aditya-Gupta1 for a review, to see if you have satisfied his ideation.
> 
> Don't worry, ur contribution is quality work. Just u have to restructure it according to our motto.
> 
> Reach out to us if u have any queries.

Should I make a new PR with all the required changes?

**Comment by rutujak24** [comment]
> Also, I researched u a bit and I say can u work as a creator? U have quite a stellar profile and u can make some potential contributions to microbytes. Go through some of the repos in miscellaneous to get an idea of what is expected from a creator. Maybe convert some good project of yours into a microbyte.
> 
> Cheers

Thanks a lot for reaching out! I would love to work as a creator, please let me know the perks of it.

**Comment by sudhanshutiwari264** [comment]
> Should I make a new PR with all the required changes?

@rutujak24 No need to create an new pr just simply commit changes in this pr !

**Comment by sudhanshutiwari264** [comment]
> Thanks a lot for reaching out! I would love to work as a creator, please let me know the perks of it.

 It seems like you are not a @CrioDo #IBelieveinDoing Hacktoberfest participant. Are you? If not kindly register yourself using [this](https://lnkd.in/gVDSD7B) link.

.

**Comment by rutujak24** [comment]
> > Should I make a new PR with all the required changes?
> 
> @rutujak24 No need to create an new pr just simply commit changes in this pr !

Since I have created a new PR #66 Please evaluated it and merge it

**Comment by rutujak24** [comment]
> > Thanks a lot for reaching out! I would love to work as a creator, please let me know the perks of it.
> 
> @Janhavi-Gautam It seems like you are not a @CrioDo #IBelieveinDoing Hacktoberfest participant. Are you? If not kindly register yourself using [this](https://lnkd.in/gVDSD7B) link.
> 
> .

 Hey @sudhanshutiwari264 are you asking me? I guess you have tagged wrong person out there. 
As far as I am concerned, I am a @CrioDo #IBelieveinDoing Hacktoberfest participant.

**Comment by sudhanshutiwari264** [comment]
@rutujak24 It's an typo mistake !
I had this doubt as you are asking for the perks and I forgot to cross check it also !

And I apologize for editing your comment as currently I am reviewing this by phone so by mistake I have edited it !

We will review your new pr asap !

**Comment by rutujak24** [comment]
> @rutujak24 It's an typo mistake !
> I had this doubt as you are asking for the perks and I forgot to cross check it also !
> 
> And I apologize for editing your comment as currently I am reviewing this by phone so by mistake I have edited it !
> 
> We will review your new pr asap !

Alright @sudhanshutiwari264 no worries.
I am asking about the perks as when I filled the @CrioDo #IBelieveinDoing Hacktoberfest form, I was told that I will get crio.do swag t-shirt and other crio.do goodies.

**Comment by sudhanshutiwari264** [comment]
@rutujak24  !
Let's not spam in the pr comments we can talk abt the perks on slack !

**Comment by rutujak24** [comment]
> @rutujak24 !
> Let's not spam in the pr comments we can talk abt the perks on slack !

Alright, Please send me slack invitation link

**Comment by rutujak24** [comment]
> Also, I researched u a bit and I say can u work as a creator? U have quite a stellar profile and u can make some potential contributions to microbytes. Go through some of the repos in miscellaneous to get an idea of what is expected from a creator. Maybe convert some good project of yours into a microbyte.
> 
> Cheers

Hey @Kevinpaulose05 I am glad to note that you found my profile engaging, I am ready to work as a creator, wherein I will add some more projects!

**Comment by Kevinpaulose05** [comment]
> > Also, I researched u a bit and I say can u work as a creator? U have quite a stellar profile and u can make some potential contributions to microbytes. Go through some of the repos in miscellaneous to get an idea of what is expected from a creator. Maybe convert some good project of yours into a microbyte.
> > Cheers
> 
> Hey @Kevinpaulose05 I am glad to note that you found my profile engaging, I am ready to work as a creator, wherein I will add some more projects!

Can u create at least one by tomorrow or Monday? Coz then next week learners can have a fresh bunch of repos to work with.
No pressure here, just try ur best.

Cheers :)

**Comment by rutujak24** [comment]
> > > Also, I researched u a bit and I say can u work as a creator? U have quite a stellar profile and u can make some potential contributions to microbytes. Go through some of the repos in miscellaneous to get an idea of what is expected from a creator. Maybe convert some good project of yours into a microbyte.
> > > Cheers
> > 
> > 
> > Hey @Kevinpaulose05 I am glad to note that you found my profile engaging, I am ready to work as a creator, wherein I will add some more projects!
> 
> Can u create at least one by tomorrow or Monday? Coz then next week learners can have a fresh bunch of repos to work with.
> No pressure here, just try ur best.
> 
> Cheers :)

I will try my best @Kevinpaulose05 , should I create a new project folder?

**Comment by amoghrajesh** [comment]
Hey, @rutujak24 you need to follow a set of instructions as we have posted on slack to create a MicroByte.
Hoping to see one good MicroByte from your end soon 😄

**Comment by rutujak24** [comment]
> Hey, @rutujak24 you need to follow a set of instructions as we have posted on slack to create a MicroByte.
> Hoping to see one good MicroByte from your end soon 😄

Hello @amoghrajesh I will go with MySQL DATABASE, "How to learn SQL queries by operating on tables
Notes: Can provide tables of data and ask users to come up with certain queries/joins - specify the correct results expected."

**Comment by Kevinpaulose05** [comment]
> > Hey, @rutujak24 you need to follow a set of instructions as we have posted on slack to create a MicroByte.
> > Hoping to see one good MicroByte from your end soon 😄
> 
> Hello @amoghrajesh I will go with MySQL DATABASE, "How to learn SQL queries by operating on tables
> Notes: Can provide tables of data and ask users to come up with certain queries/joins - specify the correct results expected."

Spot on. What u r planning is perfect. Just follow the correct workflow.

**Comment by Ak-Shaw** [comment]
@rutujak24 Actually we already have a MicroByte based on MySQL in [this](https://github.com/Crio-Bytes/Database) repo. 
Also, we've got a MicroByte proposal as given in [this](https://github.com/Crio-Bytes/Database/issues/12) issue.

Kindly go through them before you start your work, to make it as good as possible.

**Comment by YourAKShaw** [comment]
@rutujak24 Actually we already have a MicroByte based on MySQL in [this](https://github.com/Crio-Bytes/Database) repo. 
Also, we've got a MicroByte proposal as given in [this](https://github.com/Crio-Bytes/Database/issues/12) issue. 

Kindly go through them before you start your work to make it as good as possible.

Cheers. :beers:

**Comment by YourAKShaw** [comment]
@rutujak24 On second note, I suppose that you could go more adventurous by working on some other great idea. Based on your performance on this issue, seems like you can do an awesome job of creating something similar to which we don't have on stock already. That way you'll be doing us a huge favour, for we're looking for contributors who'll contribute quality MicroBytes. 

On a side note, if it's a quality MicroByte, we'll most probably showcase it on the @CrioDo website.

Cheers. :clinking_glasses:

**Comment by rutujak24** [comment]
> @rutujak24 On second note, I suppose that you could go more adventurous by working on some other great idea. Based on your performance on this issue, seems like you can do an awesome job of creating something similar to which we don't have on stock already. That way you'll be doing us a huge favour, for we're looking for contributors who'll contribute quality MicroBytes.
> 
> On a side note, if it's a quality MicroByte, we'll most probably showcase it on the @CrioDo website.
> 
> Cheers. 🥂

Thanks, @Ak-Shaw for considering me for this opportunity!
Can I go with python libraries like  Numpy, pandas Tutorial, wherein I'll cover all the commands and concepts needed to get started with data science?

**Comment by YourAKShaw** [comment]
@rutujak24 Actually you are free to go wild in any manner you want, kindly do fork the correct master repo for you MicroByte though.

But, remember one very important thing, kindly don't create a tutorial that's already available if a person knows how to Google. You are free to take inspiration from MicroBytes like [this](https://github.com/Crio-Bytes/Miscellaneous/tree/main/Building_a_Decoupled_Voice_Assistant) or [this](https://github.com/Crio-Bytes/Miscellaneous/tree/main/COVID-19%20Visualization%20using%20Pandas%20and%20Matplotlib), etc. The main point being, you need to follow the @CrioDo motto by creating a MicroByte which adheres to the **LearnByDoing approach**. Basically the learners who use your content, should be **virtually forced to think of solutions on their own, instead of it being provided to them**. That is how one learns the most. Also, kindly remember that the learning time required for your MicroByte should be 1-2 hours, the reason being they're MicroBytes.

Looking forward to your contributions!! :rocket:

**Comment by rutujak24** [comment]
> @rutujak24 Actually you free to go wild in any manner you want, kindly do fork the correct master repo for you MicroByte though.
> 
> But, remember one very important thing, kindly don't create a tutorial that's already available if a person knows how to Google. You are free to take inspiration from MicroBytes like [this](https://github.com/Crio-Bytes/Miscellaneous/tree/main/Building_a_Decoupled_Voice_Assistant) or [this](https://github.com/Crio-Bytes/Miscellaneous/tree/main/COVID-19%20Visualization%20using%20Pandas%20and%20Matplotlib), etc. The main point being, you need to follow the @CrioDo motto by creating a MicroByte which adheres to the **LearnByDoing approach**. Basically the learners who use your content, should be **virtually forced to think of solutions on their own, instead of it being provided to them**. That is how one learns the most. Also, kindly remember that the learning time required for your MicroByte should be 1-2 hours, the reason being they're MicroBytes.
> 
> Looking forward to your contributions!! 🚀

Done!
https://github.com/Crio-Bytes/Miscellaneous/pull/70

**Pull request closed without merging**
