### PR TITLE
Data Science microbyte

### LINKED ISSUE #71: Data Science Libraries Microbyte
**MicroByte Title:** Data Science Libraries

**Domain:** Data Science, Python

**Scope of learning for learners:** Hands-on knowledge of every python library needed for data science and data analytics.

**Activities:** Each Activity will contain a library, its documentation, required code for its implementation and visualization.

### PR DESCRIPTION
**Pull request by rutujak24**
## Closes #71 

<Put a x between the square brackets. Make sure you get them all>

### Checklist: 

- [x] Added activities for learners
- [x] Didn't give the solutions to the added activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Comment by rutujak24** [comment]
Hey @Kevinpaulose05 
Please review this, all the necessary changes suggested by you and the team are done.
Please feel free to close the remaining PRs.

**Review by Kevinpaulose05 — APPROVED** [review]
Good work. But u cud have chosen a better topic than this. This is a very basic tutorial of matplotlib, pandas, As clearly mentioned before there should be something that u will make the learner build through learning the concepts. All these things can be learnt by googling pretty much. u shud have come up with some application-oriented approach like [this](https://github.com/Crio-Bytes/Miscellaneous/tree/main/COVID-19%20Visualization%20using%20Pandas%20and%20Matplotlib). This is my microbyte and I am not bragging abt it. I am making u realise what u shud have done. What u did instead prepared a tutorial. The content is good, but the premise is wrong. I had recommended u to follow other microbytes that were merged. See how they are applying these base concepts to build/explain something.  Even in a completely theoretical concept of DSA ppl have beautifully contributed by explaining things in a way contributors will get engaged and challenged by. Also, the quality of this microbyte contribution u made was nowhere near to the PR u had submitted solving the linear regression problem. I don't know where u got off the wrong foot.
These were the technical aspect.

Now, there are some ethics and code of conduct of each competition/event. U have recklessly opened and closed PRs. If u know abt a GitHub PR if u keep updating ur repo the PR also gets updated, right? Then why did u consider spamming the same thing thru diff PRs. We have to keep track of lots of PRs. We cannot sort out which ones to select and which ones to ignore. 
We as Crio advocates are working relentlessly to guide and review every participant's contribution. Instead of focussing on ur potential contributions, u have crossed the line of 'reviewing' a PR. I understand this is an open-source community. So u r free to comment. But reviewing is something a maintainer(that is us) needs to do. That move of urs was totally disrespectful and hindrance in our workflow.

Please understand ur position in this competition. We may extend this competition to a general OSS Crio community. Feel free to comment then. but now u shud only be a learner/creator. Please do not overstep ur limits. 

I am approving it because I have seen ppl make drastic changes after guiding them, but u are not ready to do it, and I don't want to involve any further if u continue this way. I'm afraid if u will get another advocate's approval on this PR.
I agree a person with ur expertise may feel the need to mentor/guide fellow ppl. But that is not the case here. Ask permission first. We may/may not be superior to you but we have some responsibility that we need to take care of. Feel free to discuss and get things approved first before taking some step that is not recommended anywhere.

**Comment by rutujak24** [comment]
Hey @Kevinpaulose05 
I do agree and understand your concern but try to understand my side of the conversation. I know this is a basic microbyte, but then when I asked in a comment about this like can I proceed with this microbyte I got a positive response from one of the Advocate and I got this topic approved first, (and it is not something that I took on my own) so I moved for the but nevertheless I will be making more more quality micro bytes for this program where in I will include some real time working project also as I have worked hard on it, after the approval from one of the advocate, I didn't want to drop it anyway, coming up to the the spamming done by me with various pull requests I sincerely apologize for that as I have problem with my I GitHub command line I wasn't able to to make changes into the earlier PR hence I need to create a new and as far as the quality of this microbyte is concerned, I have included a good quality of contained which could help any beginner to cope up and understand basics of it but nevertheless I'll be making more. Also please elaborate on what exactly do you mean by crossing the limits of creator or learner because as far as I am concerned I have worked with the issues and the micro bytes so I dont think I have done something which is wrong. If any, please correct me. Also suggest me a topic for an "effective" microbyte.


Concluding, I would say that I will take care of all the things you have mentioned looking forward for more contributions together.

Cheers!

**Comment by amoghrajesh** [comment]
Hey @rutujak24!
What Kevin means by crossing the scope of a learner/creator is you reviewing this [PR](https://github.com/Crio-Bytes/Miscellaneous/pull/64). 
As a participant, we don't encourage you to review it as it the work of maintainers. Since our workflow involves counting of X number of approvals from Y reviews, we need to keep track of all the comments/reviews on a particular PR.
If anyone else out of the maintainer team does such a reviewing act, it makes it hard to keep the lane of our workflow clean.
I hope you understand what I am trying to convey.

Also, for more quality PRs from your end, a topic can be chosen from [here](https://docs.google.com/spreadsheets/d/15SY0OvF-ruqVtvWUogxRg51m6J5VZhbyGECPYIsQdi8/edit#gid=0). 
Each topic has details of what to cover too so that it doesn't become a tutorial. Make sure the topic you choose hasn't been implemented already 🛩️ 

Thanks

**Comment by rutujak24** [comment]
> Hey @rutujak24!
> What Kevin means by crossing the scope of a learner/creator is you reviewing this [PR](https://github.com/Crio-Bytes/Miscellaneous/pull/64).
> As a participant, you don't encourage you to review it as it the work of maintainers. Since our workflow involves counting of X number of approvals from Y reviews, we need to keep track of all the comments/reviews on a particular PR.
> If anyone else out of the maintainer team does such a reviewing act, it makes it hard to keep the lane of our workflow clean.
> I hope you understand what I am trying to convey.
> Thanks

Hey @amoghrajesh 
Thanks for notifying me about it, understanding the working flow, won't be reviewing any PR further!

**Review by amoghrajesh — CHANGES_REQUESTED** [review]
Hey @rutujak24!
I had a look at the content and it seems great in terms of depth. 
However, I would request you to make some small changes to make it better:

1. The intro you have given for each of the libraries in your jupyter notebook files can be cut down by a significant amount I think. Try to have points instead of paragraphs, they are easier to comprehend. (Since you are also giving the intro in readme already, you can consider cropping it off too)
2. Instead of showing how to install each of them, rather provide links - same goes with importing the libraries.
3. Rather than showing how to install htmllib, lxml etc in activity 2, provide links.
4. Try to include a final activity which can be done with usage of pandas and matplotlib so that users can test their learnings here. Don't make it too hard and DONT PROVIDE SOLUTION. (You can label it as 'Test Yourself' or so)
5. The folder structure is a bit off - put the Activity 1 and Activity 2 folders in a folder called `src` and that folder should be outside with readme. I mean -

> README
> src
>     - Activity 1 folder with contents
>     - Activity 2 folder with contents

Apart from these changes, great work!
Make these changes and we shall re review it asap 👍🏽

**Review by amoghrajesh — CHANGES_REQUESTED** [review]
Hey @rutujak24!
I just went through the content at is much better right now! 
Just one issue from my end - 
1. In the `Test Yourself` section, you are asking the users to do stuff like 'read some dataset from Kaggle' instead, be more specific and provide the exact one they should be doing so that evaluation of the learner from your end/our end becomes much easier. I mean this point applies to all of your questions - be specific about which two properties you want them to plot a scatterplot against. 
In these scatterplots too, what do you want - legend, xaxis label, yaxis label etc. All these needs to be mentioned. (This applies to all your questions)
2. Provide the cell to write code right below the question as it is already a jupyter notebook file that you have used. It seems more like a notepad right now.

A great start from your end on making the earlier changes.
Do not rush, take your time, and make these.
We will be more than happy to review it.
Thanks for our effort!

**Comment by rutujak24** [comment]
> Hey @rutujak24!
> I just went through the content at is much better right now!
> Just one issue from my end -
> 
> 1. In the `Test Yourself` section, you are asking the users to do stuff like 'read some dataset from Kaggle' instead, be more specific and provide the exact one they should be doing so that evaluation of the learner from your end/our end becomes much easier. I mean this point applies to all of your questions - be specific about which two properties you want them to plot a scatterplot against.
>    In these scatterplots too, what do you want - legend, xaxis label, yaxis label etc. All these needs to be mentioned. (This applies to all your questions)
> 2. Provide the cell to write code right below the question as it is already a jupyter notebook file that you have used. It seems more like a notepad right now.
> 
> A great start from your end on making the earlier changes.
> Do not rush, take your time, and make these.
> We will be more than happy to review it.
> Thanks for our effort!

All done!

**Comment by rutujak24** [comment]
> Hey @rutujak24!
> I just went through the content at is much better right now!
> Just one issue from my end -
> 
> 1. In the `Test Yourself` section, you are asking the users to do stuff like 'read some dataset from Kaggle' instead, be more specific and provide the exact one they should be doing so that evaluation of the learner from your end/our end becomes much easier. I mean this point applies to all of your questions - be specific about which two properties you want them to plot a scatterplot against.
>    In these scatterplots too, what do you want - legend, xaxis label, yaxis label etc. All these needs to be mentioned. (This applies to all your questions)
> 2. Provide the cell to write code right below the question as it is already a jupyter notebook file that you have used. It seems more like a notepad right now.
> 
> A great start from your end on making the earlier changes.
> Do not rush, take your time, and make these.
> We will be more than happy to review it.
> Thanks for our effort!

**Comment by rutujak24** [comment]
All the required changes are done.

**Comment by Kevinpaulose05** [comment]
@rutujak24 Activity 2 typo in referencing.

**Comment by Kevinpaulose05** [comment]
@amoghrajesh and @Ak-Shaw will be reviewing ur PR from here. I am sticking with my earlier review. This is too basic a microbyte and I understand u trying to twitch things to make it the right way. But from this topic u shud have chosen a different approach. 

Make sure ur next microbyte is not this way and that we feel a healthy complexity in ur microbyte. Also, make sure u wrap it up before 30th so that we can have a review period buffer.

**Comment by rutujak24** [comment]
> @rutujak24 Activity 2 typo in referencing.

Yea, corrected.

**Comment by rutujak24** [comment]
> @amoghrajesh and @Ak-Shaw will be reviewing ur PR from here. I am sticking with my earlier review. This is too basic a microbyte and I understand u trying to twitch things to make it the right way. But from this topic u shud have chosen a different approach.
> 
> Make sure ur next microbyte is not this way and that we feel a healthy complexity in ur microbyte. Also, make sure u wrap it up before 30th so that we can have a review period buffer.

Yea...looking forward to get this micro-byte merged.
Agreed with your views, will be taking up "Titanic Survival Project using ML" as a next one.
Open for suggestion!

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
@rutujak24 Okay, so I'll try to get to the point:

- The **README.md** should contain what we need to do in the activities. 
image
- Adding the above makes sense, but not enough of it. Basically, when a learner will try out this content, she'll have to open the src files and then she'll get to know what she actually has to do as an activity. That's the problem. Kindly add a few lines of the activity in the **README.md**, basically what needs to be done.
- Side note: **Kindly don't have a TODO list sort of an approach though**.
- Also, the first question of test yourself is vague, needs more detailing and other questions should have stuff what the graph should contain like legend, xaxis, label, etc

**Review by amoghrajesh — APPROVED** [review]
Hey!
Thanks for making the changes. 
It is much improved content now.
Hopefully we will get some learners in this one.
For the next microbytes make it a point to check out some of the earlier merged ones to get an idea of quality microbytes.

Thanks for your contribution!

**Review by YourAKShaw — APPROVED** [review]
@rutujak24 Nice work! :rocket: We appreciate your contributions. :heart_decoration: 

Keep contributing, and if you come up with premium quality ideas, your MicroByte might get published on the @CrioDo website.

**Comment by YourAKShaw** [comment]
Kindly showcase your new MicroByte in the **#microbyte-showcase** channel over at our slack workspace. Kindly use [this](https://github.com/Crio-Bytes/Demo-Repo/blob/master/Maintainer%20Resources/new-microbyte-showcase-template.md) template for the same.

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @rutujak24 for:

- [x] code
- [x] content
- [x] ideas
- [x] doc

**Pull request merged**
