### PR TITLE
Docker-Compose Infrastructure As Code 

### PR DESCRIPTION
**Pull request by sivanaikk**
This Micro byte has activities to create Docker Compose file

### CODE REVIEW

**Review by Kevinpaulose05 — CHANGES_REQUESTED** [review]
This is a totally incomplete microbyte. The theory you have provided is insufficient. a newbie will have a hard time getting to know what docker is this way. Also we already have a merged [PR](https://github.com/Crio-Bytes/Miscellaneous/tree/main/Getting_started_with_docker). Plus there is no mention of what LAMP stack is and what is its connection with docker compose. Even we are not getting what you have actually tried conveying. Pls refer to other merged PRs to understand how u have to maintain the microbyte.
Also what are the other files in 'src' folder. If they have any use u shud mention abt them too. Some of us may understand what the files are but a microbyte needs to be a Lean by doing material.
Please do honest work. Also u showcased this microbyte even before we merged it. How do u justify that? We are here to help you. Please follow the guidelines. Don't go around the system and do as u wish. Kindly see how others have made their PRs into a successfully merged microbyte.

Please tend to all issues. There may be potential here. But the way you have portrayed it, we are not at all satisfied. Please feel free to discuss. make use of this platform efficiently.

**Comment by Kevinpaulose05** [comment]
**Any leads?** @kethavathsivanaik . We were expecting u to be working these days

**Comment by sivanaikk** [comment]
@Kevinpaulose05 If I want to explain each and every keyword from code It will become some pages. That's the reason I add reference in the end.so I taught it won't be a micro byte

**Comment by Kevinpaulose05** [comment]
> @Kevinpaulose05 If I want to explain each and every keyword from code It will become some pages. That's the reason I add a reference in the end.so I taught it won't be a micro byte

We are also not expecting u to spoon feed each and every term. But to a newbie do u think it will make sense when he/she reads ur title? Even after going thru ur material, no one can get what lamp. For a docker person, it may make some sense. Refer [this](https://github.com/kethavathsivanaik/Miscellaneous/tree/main/Getting_started_with_docker)

U need to mention pre-requisites in which u shud cover installation of docker with suitable links. Then all activities should be aimed towards building something and learning along the way. Pls restructure ur microbyte into a more reformed manner. Do refer other microbytes to get an idea. Ur GitHub profile clearly shows how much of a potential contributor u are. We are pleased to have u onboard. But if u fail to contribute on time we may fail to acknowledge u. Kindly stick with us and make the changes.

**Comment by Kevinpaulose05** [comment]
As we are done with #IBelieveinDoing - Hacktoberfest edition we need to close this PR as it is incomplete according to our guidelines. We are sorry to do this but we have to close this PR to avoid any further confusion on our side. We apologise for not being to guide you in the right time. Hope you participate actively in our next month's edition of #IBelieveinDoing and other events at Crio too. Till then keep contributing and all the best!

**Pull request closed without merging**
