### PR TITLE
[MicroByte] Building a Decoupled Voice Assistant

### LINKED ISSUE #3: Building a Decoupled Voice Assistant
**MicroByte Title:** Building a Decoupled Voice Assistant

**Domain:** 
- Web
- Human Computer Interaction
- System Design

**Scope of learning for learners:** 

- Browser APIs
- Serverless Functions
- Web Development
- DevOps

**Activities:**

- Utilising Web Speech APIs
- Writing Serverless Functions
- Building a Basic Front-End
- Interacting with Serverless Functions using Fetch API
- Deploying an Application to Production

### PR DESCRIPTION
**Pull request by sudiptog81**
## Closes #3

Added a MicroByte to involve the learners to make their own voice assistants using their own backend logic from scratch.

### Checklist: 

- [x] Added activities for learners
- [x] Didn't give the solutions to the added activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Review by amoghrajesh — APPROVED** [review]
Good work @sudiptog81

**Review by sudhanshutiwari264 — APPROVED** [review]
@sudiptog81 quality is maximum great work !🎉

**Comment by YourAKShaw** [comment]
@sudiptog81 this is some premium content. Thank you for your hard work and priceless contributions. :heart_decoration:

**Comment by sudhanshutiwari264** [comment]
Nicely done @sudiptog81  . Liked ur structure and also good to see you are following the motto of crio.
Next thing that you should do is showcase this PR on microbyte-showcase channel.

Kindly follow the below mentioned format for ur msg @sudiptog81  -

All creators who have their PRs accepted and merged can show off their contribution in the microbyte-showcase channel. This will help the other participants by keeping them updated. Also, kindly refrain from spamming the channel with every minor contribution you may make. Please give a brief compiled overview of your contribution.

**Template** (Kindly stick to this format):
Title of your project #(repo-topic)
A brief overview of your project (not more than 3-5 lines). GITHUB LINK of byte must be provided. In the end of this briefing use #(languages), #(software), #(skills) tags.
Actively looking for contributors (both learners and creators). Please raise an issue first and then submit your PRs to that issue only (either after or before assigning the issue to you). Also, you can suggest how they can contribute.

**Template example:**
Concurrency #OS
Brief description. [GITHUB LINK]. #C++ #Python #Shell #Django
Actively looking for contributors. Learners can to this _ and creators can do this __. **Please raise an issue first and then submit your PRs to that issue only.**
#learnbydoing #microbyte-showcase

Needless to say keep contributing!!

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @sudiptog81 for code doc ideas content

**Pull request merged**
