### PR TITLE
COVID-19 Visualization using Pandas and Matplotlib

### LINKED ISSUE #48: COVID-19 Visualization using Pandas and Matplotlib
**MicroByte Title:** COVID-19 Visualization using Pandas and Matplotlib

**Domain:** 
- Python Programming
- Data visualization

**Scope of learning for learners:** 

- Python programming
-Data analysis using Pandas
- Data visualization using Matplotlib(.pyplot)

**Activities:**

- Comparing various statistics related to the number of cases of COVID-19 globally
- All activities exclude direct code
- A DIY challenge to test your understanding

### PR DESCRIPTION
**Pull request by Kevinpaulose05**
## Closes #48

<Put a x between the square brackets. Make sure you get them all>

### Checklist: 

- [x] Added activities for learners
- [x] Didn't give the solutions to the added activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Review by amoghrajesh — APPROVED** [review]
Hey @Kevinpaulose05 ! 
I reviewed this one thoroughly to see if I could find any mistakes, you have done a fabulous job.
Very neat content and a lot of learn by doing tasks for learners to scratch their heads.
Good work! Kudos :)

**Review by archithdwij — APPROVED** [review]
@Kevinpaulose05 It's a Premium Byte you have provided here. Very well structured and the activities are involving. Great work :100:

**Comment by archithdwij** [comment]
@all-contributors kindly add @Kevinpaulose05  for:

- [x] code
- [x] content
- [x] ideas

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @Kevinpaulose05 for doc.

**Pull request merged**
