### PR TITLE
Building logic to create the game "Tic Tac Toe"

### LINKED ISSUE #32: Fixing Bugs
MicroByte Title: Fixing Bugs 

Domain: Android Development (Java)

Prerequisites:
1. Need to know Basic Java, DSA, and Algorithm.
2. Knowledge of Android Studio.

Activities:
1. Improving layout in activity_main.xml
2. Fix bugs in MainActivity.java

### PR DESCRIPTION
**Pull request by deepak-prajapatii**
# Closes #32 
 
Checklist:
 
1. Added files or activities for learners.
2. Give the solution hints for fixing the bugs.
3. Reference material for well understand for learners.
4. Comment the code in the file where the learner needs to write the code.
5. Added images so that learner compares their project after completing it.

### CODE REVIEW

**Comment by amoghrajesh** [comment]
Hey, @deepak-prajapatii we require you to first open an issue regarding this topic following a template as given in Contributing guidelines after which we will assign this issue to you. 
Post all this you can open the PR (In this case don't close it but let it be and once we assign the issue to you, we will look into the PR :) )

**Comment by deepak-prajapatii** [comment]
> Hey, @deepak-prajapatii we require you to first open an issue regarding this topic following a template as given in Contributing guidelines after which we will assign this issue to you.
> Post all this you can open the PR (In this case don't close it but let it be and once we assign the issue to you, we will look into the PR :) )

This is my first time contributing  so I don't know so much about that. Can you help me or give me a reference in creating the issue.

**Comment by sudhanshutiwari264** [comment]
@deepak-prajapatii 
You can take help of [this blog](https://docs.github.com/en/enterprise/2.13/user/articles/creating-an-issue)
for creating issue !
[Take help of this doc to get started 👍](https://docs.google.com/document/d/1WYVo-O1--RX3hGr6hxPRm6Mz_ky1ErNDUfUZv6oEw_s/edit?usp=drivesdk)

**Comment by YourAKShaw** [comment]
> This is my first time contributing so I don't know so much about that. Can you help me or give me a reference in creating the issue.

@deepak-prajapatii 

Kindly view our [YouTube video](https://www.youtube.com/watch?v=qdSn8v9nU0g&feature=youtu.be) for the contribution workflow guidelines.

We need an issue somewhat like https://github.com/Crio-Bytes/Miscellaneous/issues/3.
We need a PR somewhat like https://github.com/Crio-Bytes/Miscellaneous/pull/1.

Feel free to drop in a message if you need further guidelines or suggestions.

**Comment by deepak-prajapatii** [comment]
> > This is my first time contributing so I don't know so much about that. Can you help me or give me a reference in creating the issue.
> 
> @deepak-prajapatii
> 
> Kindly view our [YouTube video](https://www.youtube.com/watch?v=qdSn8v9nU0g&feature=youtu.be) for the contribution workflow guidelines.
> 
> We need an issue somewhat like #3.
> We need a PR somewhat like #1.
> 
> Feel free to drop in a message if you need further guidelines or suggestions.

@Ak-Shaw As you mentioned me above i am successfully creating a issue. Now how I can merge this issue in PR.

**Comment by YourAKShaw** [comment]
To mention issue in PR you can simply select the issue number by typing # and then typing the issue number and press enter/return key.

Example: #24

**Comment by deepak-prajapatii** [comment]
> To mention issue in PR you can simply select the issue number by typing # and then typing the issue number and press enter/return key.
> 
> Example: #24

where I need to mention the issue?

**Comment by YourAKShaw** [comment]
> where I need to mention the issue?

In the PR description. Example:

## Closes #24

**Comment by deepak-prajapatii** [comment]
> Checklist:
> 
> 1. Added files or activities for learners.
> 2. Give the solution hints for fixing the bugs.
> 3. Reference material for well understand for learners.
> 4. Comment the code in the file where the learner needs to write the code.
> 5. Added images so that learner compares their project after completing it.



> > where I need to mention the issue?
> 
> In the PR description. Example:
> 
> ## Closes #24

I linked my all issues in PR description, please check my PR again.

**Comment by YourAKShaw** [comment]
Umm... No. You've got it wrong. It has to be a single issue, having description of MicroByte Creation. Kindly use `Add MicroByte` issue template for that.

**Comment by deepak-prajapatii** [comment]
> Umm... No. You've got it wrong. It has to be a single issue, having description of MicroByte Creation. Kindly use `Add MicroByte` issue template for that.

I did, please check it again.

**Comment by YourAKShaw** [comment]
@deepak-prajapatii You got it!

**Comment by YourAKShaw** [comment]
@deepak-prajapatii Checked your PR. The name of the `MicroByte folder` should be `MicroByte title` instead of `Android Development`. Further more, there seems to be plenty of room for improvement. For instance the activities on first sight seem kinda vague, need proper directions. Nevertheless, kindly don't make any move that makes it like a tutorial. It's kinda good actually, for improvement though, you can **add issues later for learners to work on**, after we merge this.

**Comment by deepak-prajapatii** [comment]
> @deepak-prajapatii Checked your PR. The name of the `MicroByte folder` should be `MicroByte title` instead of `Android Development`. Further more, there seems to be plenty of room for improvement. For instance the activities on first sight seem kinda vague, need proper directions. Nevertheless, kindly don't make any move that makes it like a tutorial. It's kinda good actually, for improvement though, you can **add issues later for learners to work on**, after we merge this.

So I don't need to make any changes.

**Comment by YourAKShaw** [comment]
> So I don't need to make any changes.

I mean, feel free to do so, there's room for improvement. We need quality MicroBytes. Yours has the potential to be one.

**Comment by deepak-prajapatii** [comment]
@Kevinpaulose05 Sorry for disturbing you. Probably my micro bytes have not reviewed yet. Please review my micro byte.

**Comment by Kevinpaulose05** [comment]
> @Kevinpaulose05 Sorry for disturbing you. Probably my micro bytes have not reviewed yet. Please review my micro byte.

Let me be frank here. This microbyte you have proposed is too small and incomplete. Incomplete in the sense that from this there is no broad topic that is being covered. Many have contributed a single microbyte but their quality is premium. The other 2 micro bytes we merged of yours is still not satisfactory but can be considered since the effort put by u and us into guiding u was immense. Talking abt the other 2, they also were potential topics but the execution was not up to the mark. But since this is OSS ppl can contribute and make expand it. Pls take some time and check out the micro bytes merged in miscellaneous, database, system design topics, u will understand where u r lacking. Don't take this as a personal attack on you but rather take this as a strong honest advice. There is a lot of room for improvement. It won't be fair to accept this PR as a microbyte and so we are closing this PR. Hope you understand my point and work on it. Having said all this we will still review any new PRs u make. But kindly don't twitch this PR into a new one. Work on something more elaborate and impactful. U have the potential, just u r not exhibiting it the right way. The biggest point I want to highlight is u r making small microbytes which by doing we may build something but learning part is totally skipped. I think even u shud agree on this point after u have a look at the other microbytes. I am not challenging ur judgement or skills but sharing the professional reality that u need to face. 

Happy Contributing!!

**Comment by deepak-prajapatii** [comment]
@Kevinpaulose05 No problem. I'll work on another micro byte and improves my fault.

**Pull request closed without merging**
