### PR TITLE
Getting Started with Docker

### PR DESCRIPTION
**Pull request by raziiiuddin**
This guide walks you through docker. It shows how docker is advantages in many ways by comparing it to Virtual Machines. The Activities include building a spring application, Writing a Dockerfile to build container images, run the containers and lastly, sharing the container images using docker hub. The guide is very useful for someone who wants not only understand the theoretical concepts of docker but also it's implementation.

### CODE REVIEW

**Review by Kevinpaulose05 — COMMENTED** [review]
Nice work on Docker intro @raziiiuddin . U have followed the guidelines well. Couple of points you should do immediately so that it can merged at the earliest.

1.  The main src folder name is off. U must have uploaded a subfolder due to which its name is off. Try to name 'src/dockerapp/dockerapp' as 'src' only. Also inside some folder names are given as a path.
2.Pls try to hide some code in activites. Like in activity 1 u can block off some code in DockerappApplication class and mention below to refer DockerappApplication.java  in case of doubts. Don't spoonfeed everything. Try and give adequate resource links at such places.
3.Create ur readme(now and also in the future) in such a way that people will understand ur 'src' folder's structure. Give specific paths. 
 
Kindly see how much of the above you can do and then i will approve it.
Cheers

**Comment by Kevinpaulose05** [comment]
> Nice work on Docker intro @raziiiuddin . U have followed the guidelines well. Couple of points you should do immediately so that it can merged at the earliest.
> 
> 1. The main src folder name is off. U must have uploaded a subfolder due to which its name is off. Try to name 'src/dockerapp/dockerapp' as 'src' only. Also inside some folder names are given as a path.
>    2.Pls try to hide some code in activites. Like in activity 1 u can block off some code in DockerappApplication class and mention below to refer DockerappApplication.java  in case of doubts. Don't spoonfeed everything. Try and give adequate resource links at such places.
>    3.Create ur readme(now and also in the future) in such a way that people will understand ur 'src' folder's structure. Give specific paths.
> 
> Kindly see how much of the above you can do and then i will approve it.
> Cheers

Also pls mention in what ways contributors can contribute to ur microbyte if there is any scope available.

**Comment by YourAKShaw** [comment]
@raziiiuddin Kindly refer to [this](https://github.com/Crio-Bytes/Miscellaneous/pull/1) as a proper format for PR description and make necessary changes by editing the above given description. 
Also, you'll need an issue too, so create an issue using the requisite template. You can use [this](https://github.com/Crio-Bytes/Miscellaneous/issues/3) as reference.

All of this help us to **maintain proper workflow**, and acts as a reference point to the contributors to think clearly regarding their contributions.

**Comment by raziiiuddin** [comment]
Thanks for the insights everyone. I'll make the changes right away. I've noticed that changing the folder structure requires to upload the files again so I am going to close this pull request and Open another one. I apologize for this inconvenience. I made some rookie mistakes that I shouldn't have. Next PR is going to be way better. Thanks.

**Comment by YourAKShaw** [comment]
@raziiiuddin You shouldn't have closed the PR. You could've just adjusted your current workflow. You should always avoid unnecessary REDO of work. It'll save time. Kindly ask suggestions from any maintainer if you have queries regarding what sort of workflow you follow.

**Pull request closed without merging**
