### PR TITLE
Building Logic to play the game "Tic Tac Toe"

### PR DESCRIPTION
**Pull request by deepak-prajapatii**

### CODE REVIEW

**Comment by amoghrajesh** [comment]
Hey,

Your Readme should be inside the folder you created and the older readme should be where it was :slightly_smiling_face:

You edited the same which was outside. Keep that one as it is and put your readme within your folder and update the PR :)

**Comment by deepak-prajapatii** [comment]
> Hey,
> 
> Your Readme should be inside the folder you created and the older readme should be where it was 🙂
> 
> You edited the same which was outside. Keep that one as it is and put your readme within your folder and update the PR :)

Okay I will

**Comment by YourAKShaw** [comment]
@deepak-prajapatii Kindly follow the new contribution guidelines as mentioned in the updated **CONTRIBUTING.md** of the main branch. 

We need an issue, similar to this format: https://github.com/Crio-Bytes/Miscellaneous/issues/3
Also a PR, similar to this format: https://github.com/Crio-Bytes/Miscellaneous/pull/1#issuecomment-711235458

You don't need to wait for yourself to get assigned, you can get right to it. It's just that it helps us to monitor your contributions in a proper workflow.

**Comment by YourAKShaw** [comment]
@deepak-prajapatii You didn't need to close this PR, you could've just adjusted a bit.

**Pull request closed without merging**
