### PR TITLE
Added all files related to micro-byte

### LINKED ISSUE #4: Cross-Platform App using Python
**MicroByte Title:** Cross-Platform App using Python

**Domain:** Python, Usage of APIs, Kivymd, a bit of UI/UX

**Scope of learning for learners:** This micro byte will walk you through the basics of building an app in Python. Here I will briefly discuss various components to be used, how to fetch data from API, and process in the background to be presented to the user. All the code will be written in Python and a bit of kivy lang which is very easy to understand. I will not explain the conversion part (python file to apk) in detail and just an overview as that is a wide domain and requires a separate byte but the application build is cross-platform. 

- A very good example of this is PyDelhi 2019. They build an android app in Python for their annual conference! 
- I build a university result portal android app which fetches data of around 13k students

**Activities:** Some activities include: 
- Basic layout of the app
- Binding input with output
- Integrating API with I/O
- How to convert it to APK

### PR DESCRIPTION
**Pull request by kaustubhgupta**
# Closes #4
# Checklist:
- [x] Added activities for learners
- [x] Didn't give the solutions to the added activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well-documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Review by amoghrajesh — APPROVED** [review]
Good work @kaustubhgupta 
Thanks for contributing!

**Review by sudhanshutiwari264 — APPROVED** [review]
@kaustubhgupta well structured ,code quality is also good !
Well done @kaustubhgupta 🎉🎉

**Comment by amoghrajesh** [comment]
Nicely done @kaustubhgupta! Liked your structure and also good to see you are following the motto of Crio.
The next thing that you should do is showcase this PR on microbyte-showcase channel.

Kindly follow the below-mentioned format for your message @kaustubhgupta -

All creators who have their PRs accepted and merged can show off their contribution to the microbyte-showcase channel. This will help the other participants by keeping them updated. Also, kindly refrain from spamming the channel with every minor contribution you may make. Please give a brief compiled overview of your contribution.

*Template* (Kindly stick to this format):
Title of your project #(repo-topic)
A brief overview of your project (not more than 3-5 lines). GITHUB LINK of byte must be provided. In the end of this briefing use #(languages), #(software), #(skills) tags.
Actively looking for contributors (both learners and creators). Please raise an issue first and then submit your PRs to that issue only (either after or before assigning the issue to you). Also, you can suggest how they can contribute.

*Template example:*
Concurrency #OS
Brief description. [GITHUB LINK]. #C++ #Python #Shell #Django
Actively looking for contributors. Learners can to this _ and creators can do this __. *Please raise an issue first and then submit your PRs to that issue only.*
#learnbydoing #microbyte-showcase

Needless to say, keep contributing!!

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @kaustubhgupta  for code doc ideas content

**Pull request merged**
