### PR TITLE
My Notes Application

### LINKED ISSUE #74: My Notes
MicroByte Title: My Notes

Domain: Android App Development

Scope of learning for learners:
1. Solutions are not given straight away.
2. Learners can contribute by #LearnByDoingApproach

Activities:
1. Fix Layout
2. Coding Phase

### PR DESCRIPTION
**Pull request by deepak-prajapatii**
# Closes #74 

Checklist:
* [x] Added files or activities for learners.
* [x]  Give the solution hints for fixing the bugs.
* [x]  Reference material for well understand for learners.
* [x]  Comment the code in the file where the learner needs to write the code.
* [x] Added images so that learner compares their project after completing it.

### CODE REVIEW

**Comment by deepak-prajapatii** [comment]
Please review my PR. If there is something wrong, please guide me.

**Comment by deepak-prajapatii** [comment]
Please review my PR. If there is something wrong, please guide me.

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
@deepak-prajapatii We highly appreciate your efforts. But, we do need some changes in the PR. The activities, the way you've portrayed it, doesn't seem engaging enough. Kindly try to make the activities engaging for the learners. **Kindly do NOT create a TODO list kind of an experience**. The activities currently seem like a TODO list. You are free to take inspiration from the other MicroBytes already present in the repo. 

Expecting some nice contribution from you. :+1:

**Comment by deepak-prajapatii** [comment]
> @deepak-prajapatii We highly appreciate your efforts. But, we do need some changes in the PR. The activities, the way you've portrayed it, doesn't seem engaging enough. Kindly try to make the activities engaging for the learners. **Kindly do NOT create a TODO list kind of an experience**. The activities currently seem like a TODO list. You are free to take inspiration from the other MicroBytes already present in the repo.
> 
> Expecting some nice contribution from you. 👍

Okay, I'll try my best for this contribution.

**Comment by deepak-prajapatii** [comment]
@Ak-Shaw I had done from my side. Please review and guide me if something wrong.

**Review by archithdwij — CHANGES_REQUESTED** [review]
@deepak-prajapatii Though you have followed the guidelines in creating the Micro-Byte(MB), the content still need some furnishing. 

- The way you have created this MB is in the form of a small documentation on how to create the notepad application. We urge you not to take your content in the path of tutorial manner. 

- Though your content provides necessary points on creating the application successfully, the ultimate aim of  LEARN BY DOING approach is not achieved here, not yet :) 

- Try creating the content that learners will find more engaging to work on. Yes, providing reference links for the process is good, but try pointing out the nook and corner that makes this application what it is and try creating micro-challenges that learners will DO first to LEARN.

Kindly remember these points and update your MicroByte. The team is expecting a Premium MB from your side since you have set your bar high from your first creator contribution and we expect you to beat your own best every time.

All the best :+1: 
Cheers!

**Comment by deepak-prajapatii** [comment]
@archithdwij My changes had to be done. Please review my PR again.

**Comment by deepak-prajapatii** [comment]
@Ak-Shaw Please review my PR. Changes had to be done from my side.

**Comment by YourAKShaw** [comment]
@deepak-prajapatii Kindly don't get me wrong, but your contribution needs to be much more significant, in case you are trying to contribute a MicroByte. I've left some friendly suggestions for you over at slack DM. Feel free to reach out to us if you're not sure, or you've got any doubts, whatsoever.

**Pull request closed without merging**
