### PR TITLE
Getting started with Docker

### LINKED ISSUE #10: Getting started with Docker
**MicroByte Title:** Getting Started with Docker

**Domain:** Docker, Containers, Cloud, DevOps, Spring(Java)

**Scope of learning for learners:** 
* Fundamental concepts of Containers and Docker
* Use Docker to containerize an application 
* Use Docker Hub to share container images

**Activities:** 
* Build a Spring Application
* Make a Dockerfile
* Build a container image and run a container
* Share container images using docker hub 
* Run the application on other machine

### PR DESCRIPTION
**Pull request by raziiiuddin**

### CODE REVIEW

**Comment by raziiiuddin** [comment]
Made changes as per Kevin's instructions and changed the folder structure. The primary reason for closing the previous PR was to change the foler structure and also improved README.md. Created an Issue as well which hadn't been done with the past PR. I'm sorry for this inconvenience but this was like my first PR ever. Hope you guys like it! Thank you!

**Review by Kevinpaulose05 — APPROVED** [review]
Please give PR description like [this](https://github.com/Crio-Bytes/Miscellaneous/pull/1). Also mentioned in the template given in .github directory.
Also try and add specific resource links wherever a new concept/term is introduced, like RestController, RequestMapping. No need to give lots of links. Just some more would be nice.
PR will be merged after another advocate approves ur PR.
Till then pls think of some issues u can open (after merging obv) for contributors to contribute to, given if there is any scope of contribution to ur microbyte. 
Rest seems fine.
Nice work,
Cheers

**Review by amoghrajesh — CHANGES_REQUESTED** [review]
Hey, @raziiiuddin I really liked the content and the structure is fine too.
I think you have posted good activities too. 
My only feedback is you can cut down some of the explanation in the start for containers, container vs VM's and stuff and provide links rather.
If permissible and possible, do add some small activities as a "Curious Cats" section for further exploration

**Comment by archithdwij** [comment]
> Hey, @raziiiuddin I really liked the content and the structure is fine too.
> I think you have posted good activities too.
> My only feedback is you can cut down some of the explanation in the start for containers, container vs VM's and stuff and provide links rather.
> If permissible and possible, do add some small activities as a "Curious Cats" section for further exploration

My thoughts too! Everything else seems perfect. If the content can be oriented in a slightly different manner that'll be easier for the learners to get started, you are good to go! Well done @raziiiuddin !

**Review by archithdwij — APPROVED** [review]
Good job! @raziiiuddin . The details in-terms of visualization will be helpful for the learners. Make sure the content is crisp as requested by @amoghrajesh . Other than this, you are good to go! Cheers!

**Comment by Kevinpaulose05** [comment]
@raziiiuddin I am merging ur PR. But it is only because ur PR is being left out for a day now and ur PR is pretty good. Kindly try and work towards @amoghrajesh 's feedback immediately.

We would appreciate a quick favor from u. For the microbyte you have submitted can u kindly open up some issues for learners (just brief simple issues should do), if there exists any scope for them. This would allow active participation in ur PR and amazing prizes await for the busiest microbyte :)

Cheers

**Comment by amoghrajesh** [comment]
closes #10

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @raziiiuddin for:

- [x] code
- [x] content
- [x] doc
- [x] ideas

**Pull request merged**
