### PR TITLE
Linear Regression with Regularization

### LINKED ISSUE #24: Linear Regression with Regularization
**MicroByte Title:** Linear Regression with Regularization

**Domain:** Machine Learning

**Scope of learning for learners:** 

1. Basic Data Analysis
2. Linear Regression Implementation
3. Ridge Regression Implementation
4. Lasso Regression Implementation
5. ElasticNet Regression Implementation

**Activities:** 

1. Activity 1 - Understand the dataset given and implement the Linear Regression Model.
2. Activity 2 - Perform analysis for assumptions to be satisfied for Linear Regression by the dataset.
3. Activity 3 - Implement Ridge, Lasso, and ElasticNet Regression and compare their performances.

### PR DESCRIPTION
**Pull request by itsadityagupta**
# Closes #24 

## Checklist

* - [x] Added activities for learners
* - [x] Didn't give the solutions to the added activities straight away
* - [x] Followed a LearnByDoing approach
* - [x] Clean and well documented code (if source code files are involved)
* - [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
@Aditya-Gupta1 seems like your selected MicroByte topic has quite potential. But it still is missing stuff like proper folder structure and a little interactive details on the activities in your README.md

Kindly refer to https://github.com/Crio-Bytes/Miscellaneous/pull/1 for inspiration. 

Also, if you plan on making tons of changes, you can convert the PR to a draft and convert it back when you're confident enough for us to review.

**Comment by itsadityagupta** [comment]
Sure @Ak-Shaw . Will improve the structure and readme file.

**Comment by itsadityagupta** [comment]
@Ak-Shaw I have modified the files as per my understanding. Please have a look at them. Also, I would like to point out that I haven't mentioned many references because I haven't taken any.
Thanks.

**Review by Kevinpaulose05 — CHANGES_REQUESTED** [review]
Great workflow. Even though u have deviated from the prescribed folder structure ur microbyte can be exempted as the format you have followed is also ok. As mentioned by you i see there are very limited resources.
Couples of things u must change-
1. U can mention setup/use of jupyter notebooks(or whatever u have used). 
2.There are numerical articles related to ur microbyte's theory.Pick up any random but appropriate articles.
3. Please hide important driving code in ur activity code using <details>Solution</details> tag. As of now there is nothing the learner needs to do. He/she can simply copy ur code to follow along.

The **reason** i am asking u to do these changes is only for your benefit. All this will maximum take u max 1 hr. A microbyte needs to be something a learner/contributor can interact and work his/her way through; never spoon-feeding them. Ur content is amzing no doubts. But as of now it is a tutorial. It needs to be a hands-on experience. 

All my suggestions are basic web searching and editing. No need to add new stuff(hoping all ur code works). More the number of contributors ur microbyte attracts, better is the chance for u to move up the leaderboard as this is an open source event.

Hoping u get my what i am implying. Feel free to discuss more if needed. Pls don't feel intimidated. U have done 80-85% of the job. Just finish it the right way.

Cheers!

**Comment by itsadityagupta** [comment]
@Kevinpaulose05 thanks for such an elaborate review. It's been a very new and enriching experience for me to make this micro-byte.
Given that I am just starting in open-source, there are some things which I haven't completely understood. But let me list down the things as per my understanding which you requested for a change:
* Add instructions to setup Jupyter Notebooks
* Add more links to underlying concepts.
* Hide some code with the detail tag so that learners can code rather than just following along.

I think this is it. Please confirm so that I can start with the changes.

**Comment by Kevinpaulose05** [comment]
> @Kevinpaulose05 thanks for such an elaborate review. It's been a very new and enriching experience for me to make this micro-byte.
> Given that I am just starting in open-source, there are some things which I haven't completely understood. But let me list down the things as per my understanding which you requested for a change:
> 
> * Add instructions to setup Jupyter Notebooks
> * Add more links to underlying concepts.
> * Hide some code with the detail tag so that learners can code rather than just following along.
> 
> I think this is it. Please confirm so that I can start with the changes.

Spot on!! Get to work :)

**Comment by itsadityagupta** [comment]
@Kevinpaulose05 I have made the following changes as requested:
* - [x] Add instructions to setup Jupyter Notebooks
* - [x] Add more links to underlying concepts.
* - [x] Hide some code with the detail tag so that learners can code rather than just following along.

Please review it once again.
Thanks.

**Review by sudhanshutiwari264 — APPROVED** [review]
Great work @Aditya-Gupta1 🎉🎉
I really liked your microbyte and topic you have selected !
It's an premium microbyte !

**Comment by itsadityagupta** [comment]
> Great work @Aditya-Gupta1 
> I really liked your microbyte and topic you have selected !
> It's an premium microbyte !

Thanks @sudhanshutiwari264

**Comment by Kevinpaulose05** [comment]
> @Kevinpaulose05 I have made the following changes as requested:
> 
> * * [x]  Add instructions to setup Jupyter Notebooks
> * * [x]  Add more links to underlying concepts.
> * * [x]  Hide some code with the detail tag so that learners can code rather than just following along.
> 
> Please review it once again.
> Thanks.

From what I gather u have removed code from the jupyter files, right?

**Comment by itsadityagupta** [comment]
Yes @Kevinpaulose05 . Also, added some more resources for users and a link to setup jupyter notebooks.

**Review by Kevinpaulose05 — APPROVED** [review]
> Yes @Kevinpaulose05 . Also, added some more resources for users and a link to setup jupyter notebooks.

Cool then. 
After merging there are a couple of things from ur side left to do. Now that u know what all is missing, please indicate them as issues so that learners can contribute to ur microbyte. Please describe the issues well so that learners will have a clear idea of what they should do. In case of any PRs to those issues, we will try notifying you on time.

Get done with this in at max an hour or so. Then get back to making new ones :) 

Keep coming up with new microbytes in this same manner. 

Cheers

**Comment by Kevinpaulose05** [comment]
Also kindly showcase this microbyte indicating there are active open issues to this. Format to be followed in slack is [this](https://github.com/Crio-Bytes/Demo-Repo/blob/master/Maintainer%20Resources/new-microbyte-showcase-template.md)

**Comment by itsadityagupta** [comment]
Thanks @Kevinpaulose05 !!

**Comment by archithdwij** [comment]
@Aditya-Gupta1 Good Job with your PR. You have followed the approach that is suitable for learners. The content seems solid and the activities are informative too. Looking forward for more contributions :100:

**Comment by Kevinpaulose05** [comment]
> Thanks @Kevinpaulose05 !!

U really have good material. Raising issues will complete ur microbyte. Else there will be a void in it, I guess u got my point already :p

**Comment by itsadityagupta** [comment]
Yes! @Kevinpaulose05 is it allowed that I can suggest the topics or open issues to my micro-byte and learners can contribute with it?

**Comment by Kevinpaulose05** [comment]
> Yes! @Kevinpaulose05 is it allowed that I can suggest the topics or open issues to my micro-byte and learners can contribute with it?

That is exactly what u need to do :)

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @Aditya-Gupta1 for:

- [x] code
- [x] doc
- [x] content
- [x] ideas

**Pull request merged**
