### PR TITLE
Add MicroByte: Learn Building Blocks of Image Processing

### LINKED ISSUE #87: Add MicroByte: Learn Building Blocks of Image Processing
**MicroByte Title:** Learn Building Blocks of Image Processing

**Domain:** Image Processing

**Scope of learning for learners:** 
- Understand how an image can be treated as an array
- What are kernels

**Activities:** 
- Decode image as an array
- Make an image from an array
- Blur an image
- Edge detection in an image

### PR DESCRIPTION
**Pull request by DesignrKnight**
### Checklist:
- [x] Added activities for learners
- [x] Didn't give the solutions to the added activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well-documented code (if source code files are involved) 
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Comment by Kevinpaulose05** [comment]
Give a brief link of python installation in pre-requisite and give installation commands of numpy and pillow too

**Comment by Kevinpaulose05** [comment]
What I understood is the learner needs to edit each function in `app.py` in each activity to see its output. Correct me if I am wrong

**Comment by DesignrKnight** [comment]
> What I understood is the learner needs to edit each function in `app.py` in each activity to see its output. Correct me if I am wrong

Yes

**Comment by Kevinpaulose05** [comment]
> > What I understood is the learner needs to edit each function in `app.py` in each activity to see its output. Correct me if I am wrong
> 
> Yes

So why not break down the codes into separate activities as 1,2,3?

**Comment by DesignrKnight** [comment]
> Give a brief link of python installation in pre-requisite and give installation commands of numpy and pillow too

Doing
numpy and pillow are added in requirements.txt and Pipfile
Will give details of installation in prerequisite

**Comment by Kevinpaulose05** [comment]
The way u have done now may be confusing to some. As people may have multiple calls. Segregate the functions into different activites

**Comment by DesignrKnight** [comment]
> > > What I understood is the learner needs to edit each function in `app.py` in each activity to see its output. Correct me if I am wrong
> > 
> > 
> > Yes
> 
> So why not break down the codes into separate activities as 1,2,3?

As in separate file?
That seems a better idea. Doing that way

**Comment by Kevinpaulose05** [comment]
> > > > What I understood is the learner needs to edit each function in `app.py` in each activity to see its output. Correct me if I am wrong
> > > 
> > > 
> > > Yes
> > 
> > 
> > So why not break down the codes into separate activities as 1,2,3?
> 
> As in separate file?
> That seems a better idea. Doing that way

Firstly number each activity. Then give its corresponding code separately rather than the way it is now

**Comment by Kevinpaulose05** [comment]
And is the code in each function incomplete?

**Comment by DesignrKnight** [comment]
> And is the code in each function incomplete?

Yes
Few lines have to added in each

**Comment by Kevinpaulose05** [comment]
> > And is the code in each function incomplete?
> 
> Yes
> Few lines have to added in each

Cool. I got the feeling from code and also after reading ur content again. Don't worry it was my error. Content is self-descriptive

**Comment by DesignrKnight** [comment]
Have done the modifications and updated

**Comment by Kevinpaulose05** [comment]
There are no articles. Pls find some relevant articles pertaining to these activities and mention them appropriately

**Comment by Kevinpaulose05** [comment]
Also is it possible to give the expected output(just a snap) of each activity? If so pls do. Also, give some real-time applications with vibrant illustrations

**Comment by DesignrKnight** [comment]
The reason I did not put article is, if I do so, almost all such articles have the code for kernel hence defeating the purpose of doing on own.

**Comment by DesignrKnight** [comment]
> Also is it possible to give the expected output(just a snap) of each activity? If so pls do. Also, give some real-time applications with vibrant illustrations

Let me do the same. I know an actual police case that used edge detection in image

**Comment by Kevinpaulose05** [comment]
> The reason I did not put article is, if I do so, almost all such articles have the code for kernel hence defeating the purpose of doing on own.

Some general reading stuff shud do. No need of technical blogs. See if u get any, no compulsion

**Comment by Kevinpaulose05** [comment]
> Also is it possible to give the expected output(just a snap) of each activity? If so pls do. Also, give some real-time applications with vibrant illustrations

Also pls look into this

**Comment by DesignrKnight** [comment]
Did all the chnages. Apologies on delay

**Comment by Kevinpaulose05** [comment]
All expected output images are not working. Check if the path given Is right

**Comment by DesignrKnight** [comment]
Fixed now. Can you see?

**Review by Kevinpaulose05 — APPROVED** [review]
Awesome work @DesignrKnight . another advocate will look into it once. U know what to do after merging. 

nice work. Cheers

**Review by archithdwij — APPROVED** [review]

**Review by sudhanshutiwari264 — APPROVED** [review]
Great work @DesignrKnight don't forget to fill this [form](https://forms.gle/ZA2VeuTDU87xmkxD7)
Ones your pr is merged!
Happy contributing !🥳🥳

**Comment by Kevinpaulose05** [comment]
@all-contributors kindly add @DesignrKnight for:

- [x] code
- [x] doc
- [x] ideas
- [x] content

**Pull request merged**
