### PR TITLE
Nikhilanand/speech to text/add

### LINKED ISSUE #42: How to create SpeechToText app
# How to create SpeechToText app

#####  What you will learn?
 In this Micro-Byte we will learn how to implement speech to text functionality in android. To enable our app to use speech to text we have to use the SpeechRecognizer class. And how to make SpeechToText android app

Activities
 ## Activity 0: How to install Android studio
## Activity- 4:Create reference of Image button  in MainActivity By findView by id
 ##  Activity- 5: How to build APK and install in device

### PR DESCRIPTION
**Pull request by Nikhilananddev**
## Closes #42 

<Put a x between the square brackets. Make sure you get them all>

### Checklist: 

- [x] Added activities for learners
- [x] Didn't give the solutions to the added activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Comment by YourAKShaw** [comment]
@Nikhilananddev Kindly edit your PR description and follow [this](https://github.com/Crio-Bytes/Miscellaneous/blob/main/.github/PULL_REQUEST_TEMPLATE/adding-microbyte.md) template for the same in case of new MicroBytes. 
Also, your PR is under review.

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
@Nikhilananddev about the current state of your PR.

**Pros**:

- Nice topic
- Scope of learning 

**Cons**:

 - Activities are not well documented enough to encourage and welcome learners

You see, don't get me wrong though, but this is kind of a serious con. The thing is that, obviously you won't spoon feed the learners through your MicroByte, they'll follow a LearnByDoing approach, but the learners need to have an brief picture of what needs to be done. That said, your activities currently are too vague for a learner to understand by just going through your README.md. The activities in the README.md should contain brief details about the activities, like when a we give brief details about the job that needs to be done. Also kinda make it interactive. Also please don't overdo it.

I hope now you have direction and can make necessary changes.

**Review by Kevinpaulose05 — CHANGES_REQUESTED** [review]
"Didn't give the solutions to the added activities straight away" - How is this condition being satisfied with ur microbyte? We can agree on the point that what u gave is an android studio tutorial with a fine example.

Here's what u need to do now:

1. Don't give away the code directly. Give hints as comments if needed. At this point there is nothing the learner needs to work on his own. He/she can simply follow ur MB to get the output.
2. Don't pin point everything. Like click on bundles/locate . There should be some things the learner figures out on their own. I can't exactly suggest u the changes but do understand what we are trying to get out of a microbyte.

**Comment by Kevinpaulose05** [comment]
Also "To get started with this micro-byte please go to any of the folders and check out is readme" heading is absurd. Take some more time if u want @Nikhilananddev . Pls do quality assurance of your microbytes beforehand.

**Comment by YourAKShaw** [comment]
**The point here:**

Kindly don't create a tutorial that's already available if a person knows how to Google. You are free to take inspiration from MicroBytes like [this](https://github.com/Crio-Bytes/Miscellaneous/tree/main/Building_a_Decoupled_Voice_Assistant) or [this](https://github.com/Crio-Bytes/Miscellaneous/tree/main/COVID-19%20Visualization%20using%20Pandas%20and%20Matplotlib), etc. The main point being, you need to follow the @CrioDo motto by creating a MicroByte which adheres to the **LearnByDoing approach**. Basically the learners who use your content, should be **virtually forced to think of solutions on their own, instead of it being provided to them**. That is how one learns the most. Also, kindly remember that the learning time required for your MicroByte should be 1-2 hours, the reason being they're MicroBytes.

**Pull request closed without merging**
