### PR TITLE
Git Fundamentals Microbyte

### LINKED ISSUE #37: New Microbyte for Git Fundamentals
MicroByte Title: Git Fundamentals
Domain: Version - Control

Scope of learning for learners:

    Understanding git and github
    Git workflow
    Git commands
   

Activities:

    Activity 1(Creating a Repo and Adding files) : Contains brief explanation about creating a repo and adding files.Also explains basic git commands.
    Activity 2(Cloning and Branching): Explains the process of cloning and the necessary of branching in git.
    Activity 3(Forking and Pull Request): Explains about forking and Pull request. This activity will not be a lot tutorialish.

### PR DESCRIPTION
**Pull request by itherohit**
## Closes #37 

<Put a x between the square brackets. Make sure you get them all>

### Checklist: 

- [x] Added activities for learners
- [x] Didn't give the solutions to the added activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
@itherohit Saying that your PR doesn't contain content would be wrong. It does contain content apparently it doesn't contain enough, for now that is. What you've accomplished to create so far shows us that you're capable of doing a far better job.

I'll get straight to the point.

**Pros**:

- Direct instructions
- Proper images

**Cons**:

- The coverage of fundamental concepts are missing.

The thing is, when you posted your issue, we were expecting that you'll cover the concepts behind Git, that'll be really genuine to do. **You shouldn't do something which could easily be googled**. I think you can do a far better job if you could add activities that leads to understanding of concepts behind Git and what makes it so powerful. You can checkout [this YT playlist](https://www.youtube.com/playlist?list=PLg7s6cbtAD17Gw5u8644bgKhgRLiJXdX4) for inspiration.

I hope you get what I'm trying to tell you.

Looking forward to improvements. Cheers. :beers: 

Also, feel free to reach out to us if you need any assistance.

**Comment by itherohit** [comment]
@Ak-Shaw Can you be more specific on what I should improve? I explained most of the git command while doing activities. I made this Microbyte for people who does not have any idea about git and Github. I am ready to improve this Microbyte!

**Comment by YourAKShaw** [comment]
@itherohit Kindly don't get me wrong.

A MicroByte is not a tutorial.
A MicroByte is an interactive activity/module based content.

When I say interactive, it means that the content virtually forces the learners to do the digging on their own, **no spoon feeding**.

So, **how can you improve?**
Well, you can work on giving activities in such a fashion in which learners can understand the concepts behind the working of Git.
You can add upon whats already there. By adding more activities/micro-activities in which learners try to learn the concepts behind Git. **Don't try to feed them with information, but curiosity**. 

If you have further queries, you are free to reach me, or any of the other advocates, on slack. We'll be more than happy to help you out.

**Review by rutujak24 — CHANGES_REQUESTED** [review]
Hey @itherohit 
Just reviewed your PR, it has covered a lot of concepts of git version control. But the following are some areas for improvements:

Firstly the content is quite similar to any git tutorial which can be easily found on google, to make your micro-byte unique you can add some more conceptual part behind the commands, the main motto is the learners should have hands-on experience from the micro-byte.

Secondly, the tutorial has more scope as GitHub and git are just not limited to these commands, adding organizations, maintaining GitHub hierarchy can be few suggestions that can be looked upon.

Btw good work with the PR!

**Comment by YourAKShaw** [comment]
We'll be moving the contents over to the [Demo-Repo](github.com/Crio-Bytes/Demo-Repo) repository of the org.

**Pull request merged**
