### PR TITLE
added a new microbyte for understanding Interfaces in Java

### LINKED ISSUE #33: New microbyte for Understanding Interfaces in Java
**MicroByte Title:** Interfaces in Java

**Domain:** Object Oriented Programming(Java)

**Scope of learning for learners:** 
   

- Creating Interfaces in Java
- Abstract Methods
- Inheriting Interfaces
- Method Overriding

**Activities:** <give a brief idea about what sort of activities this MicroByte will contain>

- Activity 1(Understanding abstract methods) : Contains brief explanation of abstract methods along with a micro-challenge/ task for the learner.
- Activity 2(Creating Interfaces in Java): A brief explanation of interfaces along with references and syntax. A micro-challenge/ task for learner to create an interface according to the specified requirements.
- Activity 3(Inheritance and Using Interface): Activity to create two new Classes, inheriting the Interface and implementing the overridden abstract methods.

### PR DESCRIPTION
**Pull request by srishti-034**
## Closes #33 

<Put a x between the square brackets. Make sure you get them all>

### Checklist: 

- [x] Added activities for learners
- [x] Didn't give the solutions to the added activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Review by amoghrajesh — CHANGES_REQUESTED** [review]
Hey, @srishti-034 I really liked the way you have put together all the content.
I would request you to make some very small changes: 

- You can crop the initial theory a bit as it looks quite big and learners must be able to cover the MB in <= 1hr

Otherwise great content!

**Comment by srishti-034** [comment]
I have reviewed and deleted unnecessary theory from the Introduction part

**Review by Kevinpaulose05 — APPROVED** [review]
Nicely done . We really appreciate the time you took into creating this amazing microbyte. 

There are a few things that you could do to notify people(especially learners) about your microbyte so that your repo will have more contributors.
1.  After merging open a couple of issues. In these issues, you should indicate learners to solve activity 1,2,3 and submit their PRs. Also any other issues you feel like opening are also welcome. We will assign those to interested learners, and if needed seek ur assistance in code review(worst case :p)
2. Showcase your microbyte(may also indicate the open issues) using [this](https://github.com/Crio-Bytes/Demo-Repo/blob/master/Maintainer%20Resources/new-microbyte-showcase-template.md) in the slack microbyte-showcase channel.

Top contributors are decided based on the amount of activity their PR has. Aforementioned steps will improve your chances.

I still feel that your microbyte will take more than 1 hour to complete and it is more of a byte than a microbyte. It's okay, nothing to worry. Also stressing on that point more is futile at this point. Please work on something new and maybe try finishing it by Sunday. Open an issue and start working on it, don't wait for it to be assigned. We can sort it out in the PR.

Well done again and Cheers!!

**Comment by Kevinpaulose05** [comment]
a personal suggestion: Improve your GitHub profile. Like by adding a profile pic and stuff. Because now people are going to see ur profile. They should get good first impressions.

**Review by amoghrajesh — APPROVED** [review]
Hey, @srishti-034 I appreciate you for making the changes quickly and presenting us with this amazing PR.
As @Kevinpaulose05 mentioned earlier, try to think of some issues to raise so that learners can benefit from this too.
It is extremely engaging and I like the way you introduce your content at the start.

Do showcase your PR once merged, using the template shared in the above comment.

Again, Well Done!

**Comment by srishti-034** [comment]
Thank so much for your appreciation and suggestions. I will surely raise some issues in the repo.

**Comment by amoghrajesh** [comment]
@all-contributors kindly add @srishti-034 for:

- [x] code
- [x] content

**Comment by Kevinpaulose05** [comment]
> Thank so much for your appreciation and suggestions. I will surely raise some issues in the repo.

Don't forget to showcase ur microbyte as mentioned before :)

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @srishti-034 for:

- [x] doc
- [x] ideas

**Pull request merged**
