### PR TITLE
PhotoFrame Application

### LINKED ISSUE #51: Coding and Debugging
MicroByte Title: Coding and Debugging

Domain: Android Development (Java)

Prerequisites:
Need to know Basic Java, DSA, and Algorithm.
Knowledge of Android Studio.

Activities:
1. Layout Improvement in activity_main.xml
2. Coding Phase in the MainActivity.java

### PR DESCRIPTION
**Pull request by deepak-prajapatii**
# Closes #51 

Checklist: 
1. Added files or activities for learners.
2. Solutions are not given straight away.
3. Reference material for well understand for learners.
4. Comment the code in the file where the learner needs to write the code.
5. Added images so that learner compares their project after completing it.

### CODE REVIEW

**Review by Kevinpaulose05 — CHANGES_REQUESTED** [review]
There are a couple of things you need to change. 

1. The screenshots u have provided are not good. 'Not good' in the sense that the screenshot is cut off abruptly at the border. If you are providing screenshots provide good ones. Or u can simply copy the code there using '>' tag.
2. Provide some JAVA/XML tutorial if possible in prerequisite.
3. u have hidden mainly changing the alpha part of the code. Critical code is still available. Try to restructure that part. The reason we emphasis on this part is that after merging u will raise issues for learners to contribute to ur repo by solving the code. This way ur repo will have more activity enabling u a better position in the leaderboard.

**Name** ur PR photoframe application. Coding and debugging is what is done. Repo name needs to be the PR name(more or less).

Also how is this solving a real-world problem? I don't see any relation. Check this out coz u should not mislead ppl with false hopes.

Tend to these matters and we will review it again. All this should take u at most 1 more hour of yours.

Cheers

**Comment by deepak-prajapatii** [comment]
@Kevinpaulose05 sure I'll try

**Comment by deepak-prajapatii** [comment]
> There are a couple of things you need to change. 
> 
> 1. The screenshots u have provided are not good. 'Not good' in the sense that the screenshot is cut off abruptly at the border. If you are providing screenshots provide good ones. Or u can simply copy the code there using '>' tag.
> 2. Provide some JAVA/XML tutorial if possible in prerequisite.
> 3. u have hidden mainly changing the alpha part of the code. Critical code is still available. Try to restructure that part. The reason we emphasis on this part is that after merging u will raise issues for learners to contribute to ur repo by solving the code. This way ur repo will have more activity enabling u a better position in the leaderboard.
> 
> **Name** ur PR photoframe application. Coding and debugging is what is done. Repo name needs to be the PR name(more or less).
> 
> Also how is this solving a real-world problem? I don't see any relation. Check this out coz u should not mislead ppl with false hopes.
> 
> Tend to these matters and we will review it again. All this should take u at most 1 more hour of yours.
> 
> Cheers

Sure I'll try

**Comment by deepak-prajapatii** [comment]
> There are a couple of things you need to change.
> 
> 1. The screenshots u have provided are not good. 'Not good' in the sense that the screenshot is cut off abruptly at the border. If you are providing screenshots provide good ones. Or u can simply copy the code there using '>' tag.
> 2. Provide some JAVA/XML tutorial if possible in prerequisite.
> 3. u have hidden mainly changing the alpha part of the code. Critical code is still available. Try to restructure that part. The reason we emphasis on this part is that after merging u will raise issues for learners to contribute to ur repo by solving the code. This way ur repo will have more activity enabling u a better position in the leaderboard.
> 
> **Name** ur PR photoframe application. Coding and debugging is what is done. Repo name needs to be the PR name(more or less).
> 
> Also how is this solving a real-world problem? I don't see any relation. Check this out coz u should not mislead ppl with false hopes.
> 
> Tend to these matters and we will review it again. All this should take u at most 1 more hour of yours.
> 
> Cheers

@Kevinpaulose05   Please review my pull request again.

**Review by Kevinpaulose05 — APPROVED** [review]
I see there is still scope of code reduction. Like some logic code in currentImage variable, layout details. See ur duty is to provide the framework. learners will have to work their way thru. So all those types of 'not so obvious code' should be removed and hints(as comments) should be written in its place. Try to do some more code reduction.

Another advocate will be reviewing it shortly before merging it. So make sure u try doing it till then. Also, wrap this up as soon as possible and start working on a new microbyte, as u r a potential creator.

Cheers!!

**Comment by deepak-prajapatii** [comment]
> I see there is still scope of code reduction. Like some logic code in currentImage variable, layout details. See ur duty is to provide the framework. learners will have to work their way thru. So all those types of 'not so obvious code' should be removed and hints(as comments) should be written in its place. Try to do some more code reduction.
> 
> Another advocate will be reviewing it shortly before merging it. So make sure u try doing it till then. Also, wrap this up as soon as possible and start working on a new microbyte, as u r a potential creator.
> 
> Cheers!!

@Kevinpaulose05 I have done from my side, please check it again if there is something wrong please guide me

**Review by Kevinpaulose05 — APPROVED** [review]
You haven't done what I had expected. But since this is ur first one I am approving it, so that can work on a new one too.  U have a quality microbyte. Thing is ppl should work their way thru the MB, not follow some pre-written steps. For this the best way is to hide the important driving code and give steps/hints in its place.  I hope u take these things into account in your next MB. 

Happy Contributing!!

**Comment by deepak-prajapatii** [comment]
> You haven't done what I had expected. But since this is ur first one I am approving it, so that can work on a new one too.  U have a quality microbyte. Thing is ppl should work their way thru the MB, not follow some pre-written steps. For this the best way is to hide the important driving code and give steps/hints in its place.  I hope u take these things into account in your next MB. 
> 
> Happy Contributing!!

Thanks!

**Comment by deepak-prajapatii** [comment]
@Kevinpaulose05 again sorry for disturbing you, this is my last micro bytes which has not been reviewed yet. Kindly reviewed it.

**Comment by Kevinpaulose05** [comment]
> @Kevinpaulose05 again sorry for disturbing you, this is my last micro bytes which has not been reviewed yet. Kindly reviewed it.

I can see the same pattern here. Trust me if we accept these we will e doing injustice do both u and Crio OSS. Contributing is important, nut contributing the right thing in the right way is what people seek. We have sufficiently guided u. Somewhere we got off track.  I suggest take some time off. No need to rush things. Review other microbytes, guidelines and then see what is lacking with these PRs. I understand u will be feeling bad about this but try and understand, we got to do it the right way. This experience will not go waste. U now know what not to do and where u r lacking w.r.t. our OSS competiton. Work on it and I assure u will come up with some amazing microbytes.  Try and keep quality > quantity, everyone prefers that :)

**Comment by deepak-prajapatii** [comment]
> > @Kevinpaulose05 again sorry for disturbing you, this is my last micro bytes which has not been reviewed yet. Kindly reviewed it.
> 
> I can see the same pattern here. Trust me if we accept these we will e doing injustice do both u and Crio OSS. Contributing is important, nut contributing the right thing in the right way is what people seek. We have sufficiently guided u. Somewhere we got off track. I suggest take some time off. No need to rush things. Review other microbytes, guidelines and then see what is lacking with these PRs. I understand u will be feeling bad about this but try and understand, we got to do it the right way. This experience will not go waste. U now know what not to do and where u r lacking w.r.t. our OSS competiton. Work on it and I assure u will come up with some amazing microbytes. Try and keep quality > quantity, everyone prefers that :)

okay i understand.

**Pull request closed without merging**
